// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fortranfctpassing_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Rfct
void Rfct(SEXP fct);
RcppExport SEXP _fortranfctpassing_Rfct(SEXP fctSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type fct(fctSEXP);
    Rfct(fct);
    return R_NilValue;
END_RCPP
}
// Rfct2
void Rfct2();
RcppExport SEXP _fortranfctpassing_Rfct2() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rfct2();
    return R_NilValue;
END_RCPP
}
// call_fortran_which_callsR
void call_fortran_which_callsR();
RcppExport SEXP _fortranfctpassing_call_fortran_which_callsR() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call_fortran_which_callsR();
    return R_NilValue;
END_RCPP
}
// call
void call();
RcppExport SEXP _fortranfctpassing_call() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call();
    return R_NilValue;
END_RCPP
}
// test_get_fortran
Rcpp::XPtr<fp> test_get_fortran();
RcppExport SEXP _fortranfctpassing_test_get_fortran() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_get_fortran());
    return rcpp_result_gen;
END_RCPP
}
// call2
void call2();
RcppExport SEXP _fortranfctpassing_call2() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call2();
    return R_NilValue;
END_RCPP
}
// call_fortran_which_call_fortran_via_c
void call_fortran_which_call_fortran_via_c();
RcppExport SEXP _fortranfctpassing_call_fortran_which_call_fortran_via_c() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call_fortran_which_call_fortran_via_c();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fortranfctpassing_Rfct", (DL_FUNC) &_fortranfctpassing_Rfct, 1},
    {"_fortranfctpassing_Rfct2", (DL_FUNC) &_fortranfctpassing_Rfct2, 0},
    {"_fortranfctpassing_call_fortran_which_callsR", (DL_FUNC) &_fortranfctpassing_call_fortran_which_callsR, 0},
    {"_fortranfctpassing_call", (DL_FUNC) &_fortranfctpassing_call, 0},
    {"_fortranfctpassing_test_get_fortran", (DL_FUNC) &_fortranfctpassing_test_get_fortran, 0},
    {"_fortranfctpassing_call2", (DL_FUNC) &_fortranfctpassing_call2, 0},
    {"_fortranfctpassing_call_fortran_which_call_fortran_via_c", (DL_FUNC) &_fortranfctpassing_call_fortran_which_call_fortran_via_c, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fortranfctpassing(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
