// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fortranfctpassing_types.h"
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// call_fortran_which_call_fortran_via_c
void call_fortran_which_call_fortran_via_c();
RcppExport SEXP _fortranfctpassing_call_fortran_which_call_fortran_via_c() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    call_fortran_which_call_fortran_via_c();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fortranfctpassing_call_fortran_which_call_fortran_via_c", (DL_FUNC) &_fortranfctpassing_call_fortran_which_call_fortran_via_c, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fortranfctpassing(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
