# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rfct2 <- function() {
    invisible(.Call(`_fortranfctpassing_Rfct2`))
}

call_fortran_which_callsR <- function() {
    invisible(.Call(`_fortranfctpassing_call_fortran_which_callsR`))
}

call_fortran_which_call_fortran_via_c <- function() {
    invisible(.Call(`_fortranfctpassing_call_fortran_which_call_fortran_via_c`))
}

