# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

call <- function() {
    invisible(.Call(`_fortranfctpassing_call`))
}

test_get_fortran <- function() {
    .Call(`_fortranfctpassing_test_get_fortran`)
}

call2 <- function() {
    invisible(.Call(`_fortranfctpassing_call2`))
}

call_fortran_which_call_fortran_via_c <- function() {
    invisible(.Call(`_fortranfctpassing_call_fortran_which_call_fortran_via_c`))
}

